### ISSUE TITLE
Login with social account Google fail

### ISSUE THREAD

**Issue by dirceudn** [ReachFive/identity-android-sdk#61]
Hi,

When I try a login with a Google social account there is an error like this:

`ReachFiveError(message=10:, code=null, exception=com.google.android.gms.common.api.ApiException: 10:, data=null)`

In the GoogleProvider.kt I have a status error like this:

`Status{statusCode=DEVELOPER_ERROR, resolution=null}`

I have no idea what kind of error is that.

Thanks[],

**Comment by Wadjetz** [comment]
Hello @dirceudn 

This error is due to a mis configuration of the google native SDK,
generally related to the application signature and the type of the API client on the Google console, 
it is necessary to follow the steps in the [documentation](https://developer.reach5.co/guides/installation/android/)

**Comment by dirceudn** [comment]
Hi,

I'll check this. Thanks :D

**Comment by axuan25** [comment]
Closing this thread for now, please don't hesitate to get back to us if you are still experiencing any issues with the SDK.
