### ISSUE TITLE
Error obtain refreshAccessToken with an AuthToken

### ISSUE THREAD

**Issue by dirceudn** [ReachFive/identity-android-sdk#63]
Hi,

##### When I try to retrieve a refresh token after a login or signup I always get this error message for example:

`ReachFiveError(message=invalid_request, code=400, exception=null, data=ReachFiveApiError(error=invalid_request, errorId=ZD2raxEqFR, errorUserMsg=Invalid form, errorDescription=Validation failed, errorDetails=[ReachFiveApiErrorDetail(field=refresh_token, message=This field is required)]))`

###### These are my login and sign up code respectively:

```
reach5.loginWithPassword(username = username, password = password, scope = listOf("offline_access", "full_write"),
                success = {
                    connector.authToken = it
                    fetchProfile(username, password, it)
               },
                failure = { error ->
                    handlerReachFiveError(error)
               }
        )
```
```
 reach5.signup(profile, scope = listOf("offline_access", "full_write"), success = { token ->
            connector.authToken = token
            Timber.tag(TAG).e("Success signup = $token")
            handleSignupProcess(username, password, token)
        }, failure = {
            //fix me check the good code error
            if (hasAlreadyAnAccount) {
                joinAccountCreated(username, password)
            } else {
                handlerSignupError(it.data)
            }
            Timber.tag(TAG).e("Failure signup = ${it.data}")
        }
        )
```
##### The authToken that I retrieve at login or sign up always comes with a refresh token null. But I don't understand why I need a refreshToken to retrieve another refreshToken as it says in the error message above.

Thanks,

**Comment by axuan25** [comment]
Hi @dirceudn !

First of all, in order for a refresh token to be included in your Reach Five `AuthToken`, your client must be configured to:
1. Enforce PKCE
2. Enable refresh tokens

Could you double check that that is the case? Without these settings, your AuthToken will not include a refresh token, and you won't be able to obtain new access tokens as a result.

Refresh tokens should be used to "refresh" your AuthToken by using the `Reach5.refreshAccessToken` method as described [here](https://developer.reach5.co/api/identity-android/#refresh-access-token). You can check the validity of the current access token with `AuthToken.expiresIn`

I hope this helps, otherwise, I'll be glad to answer your questions!

Best regards,
Chris

**Comment by dirceudn** [comment]
Hi,
Thanks for your answer  :) I'ts working :D
